FROM confluentinc/cp-kafka-connect:7.6.1

USER root

RUN confluent-hub install --no-prompt debezium/debezium-connector-postgresql:2.5.4

COPY clickhouse-kafka-connect-v1.3.5/ /usr/share/confluent-hub-components/clickhouse-kafka-connect/

ENV CONNECT_PLUGIN_PATH="/usr/share/java,/usr/share/confluent-hub-components"

USER appuser