CREATE ROLE debezium WITH LOGIN PASSWORD 'debezium';
ALTER ROLE debezium WITH REPLICATION;
GRANT CONNECT ON DATABASE postgres TO debezium;
CREATE PUBLICATION dbz_publication FOR ALL TABLES;
GRANT USAGE ON SCHEMA public TO debezium;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO debezium;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT SELECT ON TABLES TO debezium;