version: 2

sources:
  - name: clickhouse_raw
    database: clickhouse
    schema: clickhouse
    tables:
      - name: customers
        columns:
          - name: customer_id
            tests:
              - not_null
              - unique

      - name: merchants
        columns:
          - name: merchant_id
            tests:
              - not_null
              - unique

      - name: products
        columns:
          - name: product_id
            tests:
              - not_null
              - unique

      - name: orders
        loaded_at_field: order_ts
        freshness:
          warn_after: {count: 24, period: hour}
          error_after: {count: 48, period: hour}
        columns:
          - name: order_id
            tests:
              - not_null
              - unique

      - name: order_items
        columns:
          - name: order_item_id
            tests:
              - not_null
              - unique

      - name: payments
        loaded_at_field: payment_ts
        columns:
          - name: payment_id
            tests:
              - not_null
              - unique

      - name: refunds
        loaded_at_field: refund_ts
        columns:
          - name: refund_id
            tests:
              - not_null
              - unique

      - name: events
        loaded_at_field: event_ts
        freshness:
          warn_after: {count: 12, period: hour}
          error_after: {count: 24, period: hour}
        columns:
          - name: event_id
            tests:
              - not_null
              - unique